import { getAllInterviewReports, generateInterviewReport, getInterviewReportById, generateResumePdf } from "../services/interview.api"
import { useContext, useEffect } from "react"
import { useParams } from "react-router"
import { InterviewContext } from "../interview.context"


export const useInterview = () => {

    const context = useContext(InterviewContext)
    const { interviewId } = useParams()

    if (!context) {
        throw new Error("useInterview must be used within an InterviewProvider")
    }

    const { loadingState, setLoadingState, report, setReport, reports, setReports } = context

    const generateReport = async ({ jobDescription, selfDescription, resumeFile }) => {
        setLoadingState({ isLoading: true, message: "Generating your interview strategy..." })
        let response = null
        try {
            response = await generateInterviewReport({ jobDescription, selfDescription, resumeFile })
            if (!response || !response.interviewReport) {
                throw new Error("No interview report returned from server")
            }
            setReport(response.interviewReport)
            return response.interviewReport
        } catch (error) {
            console.log(error)
            throw error
        } finally {
            setLoadingState({ isLoading: false, message: '' })
        }
    }

    const getReportById = async (interviewId) => {
        setLoadingState({ isLoading: true, message: "Loading your interview report..." })
        let response = null
        try {
            response = await getInterviewReportById(interviewId)
            if (!response || !response.interviewReport) {
                throw new Error("Interview report not found")
            }
            setReport(response.interviewReport)
            return response.interviewReport
        } catch (error) {
            console.log(error)
            setReport(null)
            return null
        } finally {
            setLoadingState({ isLoading: false, message: '' })
        }
    }

    const getReports = async () => {
        setLoadingState({ isLoading: true, message: "Loading your interview plans..." })
        let response = null
        try {
            response = await getAllInterviewReports()
            setReports(response?.interviewReports || [])
            return response?.interviewReports || []
        } catch (error) {
            console.log(error)
            setReports([])
            return []
        } finally {
            setLoadingState({ isLoading: false, message: '' })
        }
    }

    const getResumePdf = async (interviewReportId) => {
        setLoadingState({ isLoading: true, message: "Generating your resume PDF..." })
        try {
            const { jsPDF } = await import('jspdf')
            const doc = new jsPDF()
            
            // Header
            doc.setFontSize(20)
            doc.text(`Resume - ${report.title || 'Job Interview'}`, 20, 30)
            
            doc.setFontSize(12)
            doc.text('Generated by Geni AI', 20, 45)
            
            // Resume text
            const resumeLines = doc.splitTextToSize(report.resume || 'Resume content not available.', 170)
            doc.text(resumeLines, 20, 60)
            
            // Skill gaps
            if (report.skillGaps?.length) {
                doc.text('Key Skill Gaps:', 20, doc.lastAutoTable?.finalY || 200)
                report.skillGaps.slice(0, 5).forEach((gap, i) => {
                    doc.text(`• ${gap.skill} (${gap.severity})`, 20, doc.lastAutoTable?.finalY || 210 + i * 7)
                })
            }
            
            doc.save(`resume_${interviewReportId}.pdf`)
        } catch (error) {
            console.error("PDF generation error:", error)
        } finally {
            setLoadingState({ isLoading: false })
        }
    }


    useEffect(() => {
        if (interviewId) {
            getReportById(interviewId)
        } else {
            getReports()
        }

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [ interviewId ])

    return { loadingState, report, reports, generateReport, getReportById, getReports, getResumePdf }

}
